dist: trusty
sudo: false
language: cpp
os:
- linux
branches:
  only:
  - master
env:
  global:
  - GOOGLETEST_HOME=$TRAVIS_BUILD_DIR/lib/googletest

script:
- cd $TRAVIS_BUILD_DIR;
  mkdir build;
  cd build;
  cmake -DCMAKE_BUILD_TYPE=Release ..;
- product_version=$(head -1 $TRAVIS_BUILD_DIR/version)
- echo Building product version v$product_version...
- make
- cd bin;
  ./rapidassist_unittest || true; #do not fail build even if a test fails.

after_success:
- echo AFTER SUCCESS!

notifications:
  email: true
