dist: trusty
sudo: false
language: cpp
os:
- linux
branches:
  only:
  - master

script:
- cd $TRAVIS_BUILD_DIR;
  mkdir build;
  cd build;
  cmake -DCMAKE_BUILD_TYPE=Release ..;
- cmake --build .;
- cd bin;
  ./rapidassist_unittest || true; #do not fail build even if a test fails.

after_success:
- echo AFTER SUCCESS!

notifications:
  email: true
